global:
  scrape_interval: 5s
  scrape_timeout: 5s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: service
    metrics_path: /
    static_configs:
      - targets:
          - 'server:9000'